version: '3.5'
services:
    wiremock:
        container_name: demo_wiremock
        image: rodolpheche/wiremock
        ports:
            - 8181:8080

    service:
        container_name: demo_service
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - wiremock
        ports:
            -   8080:8080
        environment:
            CAR_LEAD_HOST: 'http://wiremock:8080'

networks:
    default:
        ipam:
            driver: default
            config:
                -
                    subnet: 192.200.117.0/24
